### ISSUE TITLE
Error occured while sharing file using Box API

### ISSUE THREAD

**Issue by AntonGavr** [jhoerr/box-csharp-sdk-v2#53]
Hello,

We have a problem with sharing file using ShareLink/ShareFileLink method. We use free personal Box.com account. We creates a file and upload content.  But when we try to share it over BoxManager it always throws BadRequest exception.
Here is our source example:

Folder folder = boxManager.GetFolder(Folder.Root);
foreach (var file in folder.Folders)
{ 
               var getFile = boxManager.GetFile(file.Id);

```
            var sharedLink = new SharedLink()
                {
                    Access = Access.Open,
                    Permissions = new Permissions() { CanDownload = true, CanPreview = true },
                    UnsharedAt = DateTime.Now.AddYears(1)
                };
            boxManager.ShareLink(getFile, sharedLink);
```

}

Here is stacktrace:

   at BoxApi.V2.BoxRestClientBase.Try(IRestRequest request, HttpStatusCode lastResponse)
   at BoxApi.V2.BoxRestClientBase.Execute(IRestRequest request)
   at RestSharp.RestClient.Execute[T](IRestRequest request)
   at BoxApi.V2.BoxRestClientBase.ExecuteAndDeserialize[T](IRestRequest request)
   at BoxApi.V2.BoxManager.ShareFileLink(String id, SharedLink sharedLink, IEnumerable`1 fields, String etag)
   at BoxApi.V2.BoxManager.ShareLink(File file, SharedLink sharedLink, IEnumerable`1 fields, String etag)
   at Box.Program.Main(String[] args) in c:\Users\a.gavrilchik\Documents\Visual Studio 2012\Projects\Box\Box\Program.cs:line 74
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

We have tried to use your code samples with our client_id, client_secret. But it fails also.
What are we doing wrong?

We will be appreciate for any help. Looking forward your reply.

**Comment by jhoerr** [comment]
Hi Anton,

You might consider using Fiddler to capture a trace of the HTTP request that's being sent to Box.  You can then compare this to the [example request](http://developers.box.com/docs/#files-create-a-shared-link-for-a-file) documented by Box.  I'd be happy to accept a pull request if you find an fix a bug.
